// defines.h

#ifndef _DEFINES_H
#define _DEFINES_H

#define READBIT(WORD, BITSTARTPOS) ((WORD>>BITSTARTPOS)&1)
#define WRITEBIT(WORD, BITSTARTPOS, VAL) WORD = ((WORD & ~(1<<BITSTARTPOS)) | (VAL<<BITSTARTPOS))

#define READNIBBLE(WORD, NIBBLESTARTPOS) ((WORD>>NIBBLESTARTPOS)&0xF)
#define WRITENIBBLE(WORD, NIBBLESTARTPOS, VAL) WORD = ((WORD & ~(0xF<<NIBBLESTARTPOS)) | (VAL<<NIBBLESTARTPOS))

#define READBYTE(WORD, BYTESTARTPOS) ((WORD>>BYTESTARTPOS)&0xFF)
#define WRITEBYTE(WORD, BYTESTARTPOS, VAL) WORD = ((WORD & ~(0xFF<<BYTESTARTPOS)) | (VAL<<BYTESTARTPOS))

#endif
